spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/renteasy
    driver-class-name: org.postgresql.Driver
    username:
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
      show-sql: true
      defer-datasource-initialization: true

